### PR TITLE
Chore/slack notifications

### PR DESCRIPTION
**Pull request by raduachim**
**Ticket:** [#https://trello.com/c/PbmScAeE/52-slack-notifications-from-travis](https://trello.com/c/PbmScAeE/52-slack-notifications-from-travis)

**Intent:**
- add slack notifications
- since Travis does not limit the notification to a specific branch we only report on `failure` to Slack

### CODE REVIEW

**Comment by raduachim** [comment]
@lundeeell 
Good point. 
I will stop using it if we can't run the package because of it. 
It's my `https://github.com/commitizen/cz-cli` that gives me that option

**Comment by raduachim** [comment]
@lundeeell 
I will stop using `ci: ` since I cannot find anywhere. 
However if I understand correctly `fix: ` will trigger a patch release, rest will trigger a minor unless there is the word `breaking change` so the existing commits shouldn't affect I guess the existing pipeline

**Comment by lundeeell** [comment]
Oh, I didn't think that commitizen would give that option. However, chore, style and test won't trigger a release :)

**Pull request merged**
